USE ROLE SECURITYADMIN;
GRANT CREATE SCHEMA ON DATABASE CLASS_JOB_ADS TO ROLE CLASS_JOB_ADS_DBT_ROLE;

SHOW GRANTS TO ROLE CLASS_JOB_ADS_DBT_ROLE;
-- dbt-rollen ska bygga i schemana SYSADMIN skapat, inte skapa egna
REVOKE CREATE SCHEMA ON DATABASE CLASS_JOB_ADS FROM ROLE CLASS_JOB_ADS_DBT_ROLE;